### ISSUE TITLE
[ENH] Export to CDump

### ISSUE THREAD

**Issue by dtatane** [zesinger/SortingCDump#2]
This would be great to be able to export to CDump with SCD. This way we could share or reuse some similar scenes or share the work throughout a team on a dedicated project.

**Comment by zesinger** [comment]
You mean lose all the masks and dynamic work for collaboration?

**Comment by dtatane** [comment]
Consider I'm the contributor to a project. I can colorize the frames shared by the project manager. 
I could then give them back to him in CDump format. 

The PM would be in charge of filtering, sorting and creating the masks.

**Comment by zesinger** [comment]
I consider this is "quite" done with the v2.0.0
