### ISSUE TITLE
[BUG] Moving selected frames with SHIFT + CTRL

### ISSUE THREAD

**Issue by dtatane** [zesinger/SortingCDump#3]
When you start to select multiple frames with SHIFT and then add some others with CTRL, and then move the selected frames. 
All frames between the first one selected with SHIFT and the last one selected with CTRL are moved, even if some frames are not selected between them.

When using SHIFT only, it works as expected
When using CTRL only, it works as expected

**Comment by zesinger** [comment]
OK thanks, a little bit trickier than the others, but hopefully I will spot the problem quickly.

**Comment by zesinger** [comment]
I tried it but it works for me...

**Comment by dtatane** [comment]
Example :
- Select frame 13 to 11 with SHIFT
- Select frame 9 with CTRL
- Move the frames
 All frames from 9 to 13 are moved, even 10 which was not selected

**Comment by zesinger** [comment]
Fixed, thanks
