### ISSUE TITLE
[BUG] When (re)importing a file, the selected frames are kept

### ISSUE THREAD

**Issue by dtatane** [zesinger/SortingCDump#4]
The selection of frames shoudl be reset after an import.

- Import a file with TXT+
- Delete the last frames of the framestrip (for example 100 frames)
- Import new text file with TXT+ (for example 50 frames)
- The new 50 frames are selected
AND
If you hit delete, if will delete 100 frames

The selection should be reset in order, as a consequence, it will also prevent this bug

**Comment by zesinger** [comment]
Yes, sorry, that's some initializations that should be done and that I forgot, will be fixed quickly.

**Comment by zesinger** [comment]
I think everything is OK now
