### ISSUE TITLE
Return to position or move selected frames to end of strip

### ISSUE THREAD

**Issue by BorokaB** [zesinger/SortingCDump#5]
for sorting CDdump..  can there be a feature where either..  1: return to frame I was at before I moved the selected frames to their correct location.. IE..  I select frames 50101 to 50110, select cut, select a book mark, paste them at frame 300.. click button to return to 50101.  OR 2: dump selected frames to End..   Select frames 50101 to 50110 and click button and they are moved to the last frame (there by leaving me where I was originally 50100/50101..   Basically hunting frames like attached.  I usually jot down on paper where I am at (frame number)  so after the move I can return to position for sorting.. My current process is:  I actually select this frame, cut, continue searching for another rougue frame, paste beside it, then select the 2 frames, cut, and continue searching for rouge frames... Once I get about 50 "gathered together".  I paste them to the end of the strip, then finalize my processing by then cut/paste subsections of "gathered frames" to the appropriate bookmark/position they belong.
![image](https://github.com/zesinger/SortingCDump/assets/128260107/38e47d89-028e-48cb-8705-a7dad4b91d45)

**Comment by Kraken74** [comment]
I agree that having a button to return to the frame where you last cut from would be useful, instead of jotting down the frame number and having to scroll back manually.

**Comment by zesinger** [comment]
For information, it will return to the FIRST frame of the selection: if I select frames from 158 to 168 then from 18 to 26 then from 347 to 350 then move the 3 blocks and click on this button will return to frame 18 (except if the move was done before 18)

**Comment by zesinger** [comment]
Done
