### ISSUE TITLE
ISSUE: Frame strip don't works form me on ver. 2.1.0

### ISSUE THREAD

**Issue by flaben** [zesinger/SortingCDump#6]
HI Zed, 
I've an issue with SortingCDump v. 2.1.0 and my principal computer to edit colorizing (my house). When I open someone project  (p. e. Dr. Who), the frame strip shown empty but making click over, shown the first frames, but no other effect over. If make click again, the frame strip clear to black.
The ver. 2.0.0 works fine for me.
I've three computers:
- One Intel i5 with 8Gb of RAM with one nvidia GTX710 (v. 2.1.0 works fine). Is in my official work, but i can use it only on free time at work. Little time actually.
- One laptop with an AMD A10 with 12Gb of RAM and RADEON R5 (integrated with shared memory). Is the computer where I'm colorizing the roms and works fine with ColorizeDMD and SortingCDump to ver. 2.0.0
- The VPin computer (AMD A8, 8GB RAM, nvidia GTX750Ti), but don´t works for SortingCDump because are missing librarys
Don't hesitate question me if you need more information over issue

Regards

**Comment by Kraken74** [comment]
Sounds like the same issue I'm experiencing.  Sometimes when I open my project in SCD, the frame strip is completely black.  To fix the issue, I resize the window and the frames appear.

**Comment by flaben** [comment]
> Sounds like the same issue I'm experiencing.  Sometimes when I open my project in SCD, the frame strip is completely black.  To fix the issue, I resize the window and the frames appear.

Yes, when I resize the window the frames appears but I can't move over the frame strip, only show the first frames. It's locked. The version 2.0.0 works right 

What is your graphics card, Kraken?

**Comment by zesinger** [comment]
Sorry guys, I'm about to start working on the CDMD and SCD issues, perhaps a multiple of 4 issue with openGL, gonna try to fix that

**Comment by flaben** [comment]
> > Sounds like the same issue I'm experiencing.  Sometimes when I open my project in SCD, the frame strip is completely black.  To fix the issue, I resize the window and the frames appear.
> 
> Yes, when I resize the window the frames appears but I can't move over the frame strip, only show the first frames. It's locked. The version 2.0.0 works right
> 
> What is your graphics card, Kraken?

About my answer to Kraken, today I have a clue: if make bigger the window with the mouse, the frame stripe show the frames from project but if make click on the stripe I can make nothing over it, but if I maximize the screen with the "Maximize" button from the form, the frame stripe works fine, mouse and keys.

**Comment by Kraken74** [comment]
My graphics card is an AMD FirePro m4000 from 2012, in a HP Elitebook mobile workstation.

**Comment by zesinger** [comment]
fixed, thanks
